name: Run the integration tests

on:
  workflow_dispatch:

env:
  # This is Dart 3.0.x
  FLUTTER_MIN_SDK: '3.10.6'

jobs:
  macos:
    name: "Run tests on Desktop"
    strategy:
      matrix:
        include:
          - os: macos
            device: macos
          - os: windows
            device: windows
          - os: ubuntu
            device: linux
          - os: ubuntu
            device: chrome
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter test --ci integration_test -d ${{ matrix.device }}
        working-directory: example
